import 'package:equatable/equatable.dart';
import 'package:flutter/material.dart';
import 'package:google_maps_flutter/google_maps_flutter.dart';

const defaultPadding = 16.0;
const primaryColor = Colors.white;
const textColor = Color(0xFF318E99);
List<String> csvc = [
  'assets/icons/air_conditioner.svg',
  'assets/icons/balcony.svg',
  'assets/icons/interior.svg',
  'assets/icons/pet.svg',
  'assets/icons/cctv.svg',
  'assets/icons/guard.svg',
  'assets/icons/pool.svg',
  'assets/icons/pet.svg',
  'assets/icons/pet.svg',
];

class House extends Equatable {
  final String id;
  final String imgSrc, location, price, category, description, owner, avatar;
  final int numOfBed, numOfBath, area;
  final List<String> imgList;
  final LatLng latLocation;

  House(
      {this.owner,
      this.id,
      this.avatar,
      this.description,
      this.imgList,
      this.imgSrc,
      this.location,
      this.price,
      this.numOfBed,
      this.numOfBath,
      this.area,
      this.latLocation,
      this.category});

  @override
  List<Object> get props => [
        id,
        owner,
        avatar,
        description,
        imgList,
        imgSrc,
        location,
        price,
        numOfBed,
        numOfBath,
        area,
        latLocation,
        category
      ];
}

List<House> houses = [
  House(
      id: '1',
      area: 80,
      numOfBath: 1,
      numOfBed: 2,
      location:
          '3 Nguyễn Bỉnh Khiêm, Phường Bến Nghé, Quận 1, Thành Phố Hồ Chí Minh',
      price: "35,000,000 mỗi tháng",
      imgSrc: 'assets/images/nha.jpg',
      category: 'Căn hộ',
      description:
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable",
      imgList: [
        'assets/images/noithat1.jpg',
        'assets/images/noithat2.jpg',
        'assets/images/noithat3.jpg',
        'assets/images/noithat4.jpg',
        'assets/images/noithat5.jpg'
      ],
      owner: 'Cường Nguyễn',
      avatar: 'assets/images/avatar1.png',
      latLocation: LatLng(10.78558819984757, 106.70663696833627)),
  House(
      id: '2',
      area: 80,
      numOfBath: 1,
      numOfBed: 2,
      location: '1 Nguyễn Cư Trinh, Quận 1, Thành Phố Hồ Chí Minh',
      price: "35,000,000 mỗi tháng",
      imgSrc: 'assets/images/nha1.jpg',
      category: 'Chung cư',
      imgList: [
        'assets/images/noithat1.jpg',
        'assets/images/noithat2.jpg',
        'assets/images/noithat3.jpg',
        'assets/images/noithat4.jpg',
        'assets/images/noithat5.jpg'
      ],
      owner: 'Long Đỗ',
      avatar: 'assets/images/avatar2.png',
      description:
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable",
      latLocation: LatLng(10.764281398809217, 106.68965913340197)),
  House(
      id: '3',
      area: 200,
      numOfBath: 3,
      numOfBed: 6,
      location: '92 - 94 Nam Kỳ Khởi Nghĩa, Quận 1, Thành Phố Hồ Chí Minh',
      price: "4,000,000đ",
      imgSrc: 'assets/images/nha2.jpg',
      category: 'Nhà trọ',
      imgList: [
        'assets/images/noithat1.jpg',
        'assets/images/noithat2.jpg',
        'assets/images/noithat3.jpg',
        'assets/images/noithat4.jpg',
        'assets/images/noithat5.jpg'
      ],
      owner: 'Hào Đinh',
      avatar: 'assets/images/avatar3.jpg',
      description:
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable",
      latLocation: LatLng(10.772815969366393, 106.70123569717161)),
  House(
      id: '4',
      area: 80,
      numOfBath: 1,
      numOfBed: 2,
      location:
          '3 Nguyễn Bỉnh Khiêm, Phường Bến Nghé, Quận 1, Thành Phố Hồ Chí Minh',
      price: "35,000,000 mỗi tháng",
      imgSrc: 'assets/images/nha.jpg',
      category: 'Căn hộ',
      description:
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable",
      imgList: [
        'assets/images/noithat1.jpg',
        'assets/images/noithat2.jpg',
        'assets/images/noithat3.jpg',
        'assets/images/noithat4.jpg',
        'assets/images/noithat5.jpg'
      ],
      owner: 'Cường Nguyễn',
      avatar: 'assets/images/avatar1.png',
      latLocation: LatLng(10.78558819984757, 106.70663696833627)),
  House(
      id: '5',
      area: 80,
      numOfBath: 1,
      numOfBed: 2,
      location: '1 Nguyễn Cư Trinh, Quận 1, Thành Phố Hồ Chí Minh',
      price: "35,000,000 mỗi tháng",
      imgSrc: 'assets/images/nha1.jpg',
      category: 'Chung cư',
      imgList: [
        'assets/images/noithat1.jpg',
        'assets/images/noithat2.jpg',
        'assets/images/noithat3.jpg',
        'assets/images/noithat4.jpg',
        'assets/images/noithat5.jpg'
      ],
      owner: 'Long Đỗ',
      avatar: 'assets/images/avatar2.png',
      description:
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable",
      latLocation: LatLng(10.764281398809217, 106.68965913340197)),
  House(
      id: '6',
      area: 200,
      numOfBath: 3,
      numOfBed: 6,
      location: '92 - 94 Nam Kỳ Khởi Nghĩa, Quận 1, Thành Phố Hồ Chí Minh',
      price: "4,000,000đ",
      imgSrc: 'assets/images/nha2.jpg',
      category: 'Nhà trọ',
      imgList: [
        'assets/images/noithat1.jpg',
        'assets/images/noithat2.jpg',
        'assets/images/noithat3.jpg',
        'assets/images/noithat4.jpg',
        'assets/images/noithat5.jpg'
      ],
      owner: 'Hào Đinh',
      avatar: 'assets/images/avatar3.jpg',
      description:
          "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable",
      latLocation: LatLng(10.772815969366393, 106.70123569717161)),
];

List<House> likedHouses = [];

List<String> province = ["Hồ Chí Minh", "Hà Nội", "Đà Nẵng"];
List<String> district = [
  "Quận 1",
  "Quận 2",
  "Quận 3",
  'Quận 4',
  "Quận 5",
  "Quận 6",
  "Quận 7",
  'Quận 8',
  "Quận 9",
  "Quận 10",
  "Quận 11",
  'Quận 12',
  'Quận Bình Tân',
  'Quận Bình Thạnh',
  'Quận Gò Vấp',
  'Quận Phú Nhuận',
  'Quận Tân Bình',
  'Quận Tân Phú',
  'Quận Thủ Đức',
  'Huyện Bình Chánh',
  'Huyện Cần Giờ',
  'Huyện Củ Chi',
  'Huyện Hóc Môn',
  'Huyện Nhà Bè'
];

class District {
  String name;
  List<String> commune;
  District({this.name, this.commune});
}

List<District> districts = [
  District(name: "Quận 1", commune: [
    'Phường Bến Nghé',
    'Phường Bến Thành',
    'Phường Cầu Kho',
    'Phường Cầu Ông Lãnh',
    'Phường Cô Giang',
    'Phường Đa Kao',
    'Phường Nguyễn Cư Trinh',
    'Phường Nguyễn Thái Bình',
    'Phường Phạm Ngũ Lão',
    'Phường Phường Tân Định',
  ]),
  District(name: "Quận 2", commune: [
    'Phường An Khánh',
    'Phường An Lợi Đông',
    'Phường An Phú',
    'Phường Bình An',
    'Phường Bình Khánh',
    'Phường Bình Trưng Đông',
    'Phường Bình Trưng Tây',
    'Phường Cát Lái',
    'Phường Thạnh Mỹ Lợi',
    'Phường Thảo Điền',
    'Phường Thủ Thiêm'
  ]),
  District(name: "Quận 3", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
  ]),
  District(name: "Quận 4", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 16',
    'Phường 18',
  ]),
  District(name: "Quận 5", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15'
  ]),
  District(name: "Quận 6", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
  ]),
  District(name: "Quận 7", commune: [
    'Phường Bình Thuận',
    'Phường Phú Mỹ',
    'Phường Phú Thuận',
    'Phường Tân Hưng',
    'Phường Tân Kiểng',
    'Phường Tân Phong',
    'Phường Tân Phú',
    'Phường Tân Quy',
    'Phường Tân Thuận Đông',
    'Phường Tân Thuận Tây',
  ]),
  District(name: "Quận 8", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 16',
  ]),
  District(name: "Quận 9", commune: [
    'Phường Hiệp Phú',
    'Phường Long Bình',
    'Phường Long Phước',
    'Phường Long Thạnh Mỹ',
    'Phường Long Trường',
    'Phường Phú Hữu',
    'Phường Phước Bình',
    'Phường Phước Long A',
    'Phường Phước Long B',
    'Phường Tân Phú',
    'Phường Tăng Nhơn Phú A',
    'Phường Tăng Nhơn Phú B',
    'Phường Trường Thạnh',
  ]),
  District(name: "Quận 10", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15'
  ]),
  District(name: "Quận 11", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 16',
  ]),
  District(name: "Quận 12", commune: [
    'Phường An Phú Đông',
    'Phường Đông Hưng Thuận',
    'Phường Hiệp Thành',
    'Phường Tân Chánh Hiệp',
    'Phường Tân Hưng Thuận',
    'Phường Tân Thới Hiệp',
    'Phường Tân Thới Nhất',
    'Phường Thạnh Lộc',
    'Phường Thạnh Xuân',
    'Phường Thới An',
    'Phường Trung Mỹ Tây',
  ]),
  District(name: "Quận Bình Tân", commune: [
    'Phường An Lạc',
    'Phường An Lạc A',
    'Phường Bình Hưng Hòa',
    'Phường Bình Hưng Hòa A',
    'Phường Bình Hưng Hòa B',
    'Phường Bình Trị Đông',
    'Phường Bình Trị Đông A',
    'Phường Bình Trị Đông B',
    'Phường Tân Tạo',
    'Phường Tân Tạo A',
  ]),
  District(name: "Quận Thủ Đức", commune: [
    'Phường Bình Chiểu',
    'Phường Bình Thọ',
    'Phường Hiệp Bình Chánh',
    'Phường Hiệp Bình Phước',
    'Phường Linh Chiểu',
    'Phường Linh Ðông',
    'Phường Linh Tây',
    'Phường Linh Trung',
    'Phường Linh Xuân',
    'Phường Tam Bình',
    'Phường Tam Phú',
    'Phường Trường Thọ',
  ]),
  District(name: "Quận Tân Phú", commune: [
    'Phường Hiệp Tân',
    'Phường Hòa Thạnh',
    'Phường Phú Thạnh',
    'Phường Phú Thọ Hòa',
    'Phường Phú Trung',
    'Phường Sơn Kỳ',
    'Phường Tân Quý',
    'Phường Tân Sơn Nhì',
    'Phường Tân Thành',
    'Phường Tân Thới Hòa',
    'Phường Tây Thạnh',
  ]),
  District(name: "Quận Tân Bình", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
  ]),
  District(name: "Quận Phú Nhuận", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 17',
  ]),
  District(name: "Quận Gò Vấp", commune: [
    'Phường 1',
    'Phường 3',
    'Phường 4',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 8',
    'Phường 9',
    'Phường 10',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 16',
    'Phường 17',
  ]),
  District(name: "Quận Bình Thạnh", commune: [
    'Phường 1',
    'Phường 2',
    'Phường 3',
    'Phường 5',
    'Phường 6',
    'Phường 7',
    'Phường 11',
    'Phường 12',
    'Phường 13',
    'Phường 14',
    'Phường 15',
    'Phường 17',
    'Phường 19',
    'Phường 21',
    'Phường 22',
    'Phường 24',
    'Phường 25',
    'Phường 26',
    'Phường 27',
    'Phường 28',
  ]),
  District(name: "Huyện Bình Chánh", commune: [
    'Xã An Phú Tây',
    'Xã Bình Chánh',
    'Xã Bình Hưng',
    'Xã Bình Lợi',
    'Xã Đa Phước',
    'Xã Hưng Long',
    'Xã Lê Minh Xuân',
    'Xã Phạm Văn Hai',
    'Xã Phong Phú',
    'Xã Quy Đức',
    'Xã Tân Kiên',
    'Xã Tân Nhựt',
    'Xã Tân Quý Tây',
    'Xã Vĩnh Lộc A',
    'Xã Vĩnh Lộc B',
  ]),
  District(name: "Huyện Cần Giờ", commune: [
    'Xã An Thới Đông',
    'Xã Bình Khánh',
    'Xã Long Hòa',
    'Xã Lý Nhơn',
    'Xã Tam Thôn Hiệp',
    'Xã Thạnh An',
  ]),
  District(name: "Huyện Củ Chi", commune: [
    'Thị Trấn Củ Chi ',
    'Xã An Nhơn Tây',
    'Xã An Phú',
    'Xã Bình Mỹ',
    'Xã Hòa Phú',
    'Xã Nhuận Đức',
    'Xã Phạm Văn Cội',
    'Xã Phú Hòa Đông',
    'Xã Phú Mỹ Hưng',
    'Xã Phước Hiệp',
    'Xã Phước Thạnh',
    'Xã Phước Vĩnh An',
    'Xã Tân An Hội',
    'Xã Tân Phú Trung',
    'Xã Tân Thạnh Đông',
    'Xã Tân Thạnh Tây',
    'Xã Tân Thông Hội',
    'Xã Thái Mỹ',
    'Xã Trung An',
    'Xã Trung Lập Hạ',
    'Xã Trung Lập Thượng',
  ]),
  District(name: "Huyện Hóc Môn", commune: [
    'Xã Bà Điểm',
    'Xã Đông Thạnh',
    'Xã Nhị Bình',
    'Xã Tân Hiệp',
    'Xã Tân Thới Nhì',
    'Xã Tân Xuân',
    'Xã Thới Tam Thôn',
    'Xã Trung Chánh',
    'Xã Xuân Thới Đông',
    'Xã Xuân Thới Sơn',
    'Xã Xuân Thới Thượng',
  ]),
  District(name: "Huyện Nhà Bè", commune: [
    'Thị Trấn Nhà Bè',
    'Xã Hiệp Phước',
    'Xã Long Thới',
    'Xã Nhơn Đức',
    'Xã Phú Xuân',
    'Xã Phước Kiển',
    'Xã Phước Lộc',
  ]),
];
